#define the latest nodejs image  to build from
FROM node:latest-alpine
#create a working directory
WORKDIR /usr/src/app
#copy package.json file under the working directory 
COPY package.json /usr/src/app
# install all the dependencies 
RUN npm install
#copy all your files under the working directory
COPY . /usr/src/app
#expose the port 4000
EXPOSE 3000
#start nodejs server 
CMD npm start